/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iCHGtOdbgAD
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SelectValue, SelectTrigger, SelectLabel, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { CardContent, Card } from "@/components/ui/card"
import { Space } from "lucide-react"

export function DashboardComponent() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <header className="flex items-center h-16 px-4 border-b md:px-6">
        <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="">
          <span className="sr-only">AymenBNB</span>
          <div>
  <h4>AymenBNB</h4>
  
</div>
<div></div>

        </Link>
        <form className="flex-1 ml-auto">
          <div className="relative">
            <IconSearch className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input
              className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
              placeholder="Op zoek naar iets nieuws?"
              type="search"
            />
            <Button className="absolute right-0 top-0 mt-2 mr-2" type="submit" variant="default">
              Zoeken
            </Button>
          </div>
        </form>
      </header>
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <section className="grid gap-2 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2">
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Selecteer uw budget" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectLabel>Budgetbereik</SelectLabel>
                <SelectItem value="0-1000">€ 50 - € 199</SelectItem>
                <SelectItem value="1001-2000">€ 200 - € 299</SelectItem>
                <SelectItem value="2001-3000">€ 300 - € 399</SelectItem>
                <SelectItem value="3001-4000">€ 400 - € 500</SelectItem>
                <SelectItem value="4000+">$4000+</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Type Accommodatie" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectLabel>Accommodatie</SelectLabel>
                <SelectItem value="1">Hotel</SelectItem>
                <SelectItem value="2">Appartement</SelectItem>
                <SelectItem value="3">Lodge</SelectItem>
                <SelectItem value="4">Huis</SelectItem>
                <SelectItem value="5">Villa</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>

  <div>
  <h4>3 accommodaties gevonden</h4>
</div>
        </section>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 mt-4">
          <Card>
            <img
              alt="Accommodatie in Eindhoven"
              className="object-cover w-full h-80"
              height="200"
              src="https://cdn.discordapp.com/attachments/1125046048105185360/1180233845891674302/Untitled-2.png?ex=657cad6c&is=656a386c&hm=8a3be871f5d33b01d44a724f460fa2e6bb061ec9622e28905b90b1b62c06b5c0&"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardContent>
              <h3 className="font-bold text-lg">Accommodatie in Eindhoven</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">Cosy Cabin in het bos.</p>
              <h3 className="font-bold text-gray-500 dark:text-gray-400">€ 175 per nacht </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">Professionele host</p>
              <div className="flex justify-between items-center mt-4">
                <Button variant="default">Bekijk Accommodatie</Button>
                <div className="px-2 py-1 bg-red-500 text-white text-sm rounded">🔥 Hot Pick</div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Accommodatie in Brussel"
              className="object-cover w-full h-80"
              height="200"
              src="https://cdn.discordapp.com/attachments/1125046048105185360/1180234275690393720/tgr.png?ex=657cadd3&is=656a38d3&hm=647c582420c558635866e3160ac8ef68febce2c503845b0b1d842be52a16e9fe&"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardContent>
              <h3 className="font-bold text-lg">Accommodatie in Brussel</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">Appartement in Brussel-Midi.</p>
              <h3 className="font-bold text-gray-500 dark:text-gray-400">€ 75 per nacht </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">Individuele host</p>
              <Button className="mt-4" variant="default">
              Bekijk Accommodatie
              </Button>
            </CardContent>
          </Card>
          <Card>
            <img
              alt="Luxe Hotel - Antwerpen-Centraal"
              className="object-cover w-full h-80"
              height="200"
              src="https://cdn.discordapp.com/attachments/1125046048105185360/1180235403131900004/Untitled-2.png?ex=657caedf&is=656a39df&hm=d5fe410ef5e1cafedf0b54ff5b8615e3f5a6a8bf06581224b47d73bb0dcf0edc&"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
            <CardContent>
              <h3 className="font-bold text-lg">Luxe Hotel - Antwerpen-Centraal</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">Luxueuze hotel gelegen in het hartje van Antwerpen.</p>
              <h3 className="font-bold text-red-500 dark:text-red-400">🔥 € 89 per nacht </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">Beheerd door geregistreerd bedrijf </p>
              <Button className="mt-4" variant="default">
              Bekijk Accommodatie
              </Button>
              </CardContent>  
              </Card>
          
        </div>
      </main>
    </div>
  )
}


function IconSearch(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function IconHome(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}
